### ISSUE TITLE
Textadept 10.2 renamed spawn() to os.spawn() and broke textredux.ctags

### ISSUE THREAD

**Issue by pbgc** [rgieseke/textredux#41]
https://foicica.com/textadept/CHANGELOG.html

"Renamed spawn() to os.spawn()."

I changed ctags.lua to user os.spawn and it's working.

Another question.... 
I'm using OSX and installed ctags with: brew install ctags
I have a key binded to textredux.ctags.goto_symbol and it's works nicely IF I launch textadpet in the terminal with "ta" or with /Applications/Textadept.app/Contents/MacOS/textadept_osx but don't work (no message presented) when I launch clicking in the Textadept.app icon.
Any clue about this ?

Thanks in advance!

Pedro Costa

**Comment by rgieseke** [comment]
Thanks for the heads-up! This should be fixed in master.

As for the PATH issue, this is a problem on Mac, see e.g. here https://superuser.com/questions/476752/setting-environment-variables-in-os-x-for-gui-applications#541068

When you put `os.getenv("PATH")` in the command entry you will likely also get:
/usr/bin:/bin:/usr/sbin:/sbin

So any additional path would not be picked up either, still leaving user confused.
There have been some discussions in the past on the mailing list and other Mac editors have come up with different solutions, for Textadept a shell script `~/.textadept/osx_env.sh` will be sourced where you can set `PATH` used for Textadept:

https://foicica.com/textadept/manual.html#Mac.OSX.Environment.Variables

I think you would have to do something like
```shell
export PATH=/usr/local/bin:/usr/bin 
```
Maybe you could also try sourcing a file that you share with your other shell path setup to avoid duplication.

An alternative workaround is to set the path to `ctags` explicitly:

```
local textredux = require("textredux")
textredux.hijack()
textredux.ctags.CTAGS = '/usr/local/bin/ctags --sort=yes --fields=+K-f'
keys.cg = textredux.ctags.goto_symbol
```

**Comment by pbgc** [comment]
Thank you very much !
It worked great!

**Comment by rgieseke** [comment]
Great to hear!
